# This is a basic workflow that is manually triggered

name: smzdm签到

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '10 0 * * *'
  # watch:
  #   types: [started]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: '安装依赖包'
        run: pip install -r ./requirements.txt

      - name: '运行 Hifiti签到'
        run: python3 function/smzdm/smzdm.py
        env:
          SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
          SENDKEY: ${{ secrets.SENDKEY }}
          OS_TZ: ${{ secrets.OS_TZ }}
